language: java

jdk:
  - openjdk12

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="6df998b7-50db-4523-86b5-a9d80fb0ffcc"

notifications:
  email:
    recipients:
      - frolovolegvladimirovich@gmail.com
    on_success: never # default: change
    on_failure: always # default: always